### ISSUE TITLE
Sub Issue : #84 : Create Collision Primitives for use with the collision system

### ISSUE THREAD

**Issue by neomonkeus** [niftools/blender_nif_plugin#110]
Adding custom primitive types would allow us to represent havok collision better, storing specific have custom props. It would also remove some of the processing involved with shape mismatching and give more precise mapping back to the actual havok shape's values.

ref #84

**Comment by HENDRIX-ZT2** [comment]
What does 'primitives' mean in the context of this issue? As in a premade 3D shape that is used to represent colliders? If so, the issue can be closed as we've got that covered. @neomonkeus
