### ISSUE TITLE
Unique naming for bones

### ISSUE THREAD

**Issue by Ghostwalker71** [niftools/blender_nif_plugin#123]
Bones are not exposed in the unique naming block so do not get an adjusted name if the bone already exists in the blender scene which causes the script to fail.

**Comment by HENDRIX-ZT2** [comment]
Fixed by PR #289.
Blender bones now store their original NIF name as a property.
Nifs with several bone nodes sharing the same name (eg. ZT2 `PeafowlCommon_Adult_M.nif` has three `FootBackLeft` nodes) export back correctly as well.
