### ISSUE TITLE
Material code improvements

### ISSUE THREAD

**Issue by neomonkeus** [niftools/blender_nif_plugin#152]
Implement various as mentioned in #151
- [x] Material textureslot - Remove try catches
- [x] Revert Change for default case - https://github.com/niftools/blender_nif_plugin/pull/151/files#diff-e81919c52cf6e7c5d7a51bf6123e1e07R520
- [x] Refactor to object level - https://github.com/niftools/blender_nif_plugin/pull/151/files#diff-18b999f1f76a591735970bc4475214dfR267

**Comment by HENDRIX-ZT2** [comment]
no longer valid, can be closed off

**Comment by neomonkeus** [comment]
Updated current release with this ticket.
