### ISSUE TITLE
Mesh Export : Unweighted vertices

### ISSUE THREAD

**Issue by neomonkeus** [niftools/blender_nif_plugin#172]
The scripts throw an AttributeError MeshHelper "context" attribute not found when attempting to export a mesh which has a skinned mesh and armature with unweighted vertices.

Reported by misternad
Also seen by tktk - http://www50.atwiki.jp/skyrim_mod/pages/55.html

**Comment by HENDRIX-ZT2** [comment]
This has been fixed, no longer valid, can be closed off.

**Comment by neomonkeus** [comment]
I will include it in the latest release notes.
