### ISSUE TITLE
Vertex Color Import Layer creation

### ISSUE THREAD

**Issue by neomonkeus** [niftools/blender_nif_plugin#18]
On import, vertex colors are imported to a Vertex Color Layer. Only one Vertex Color Layer should being created per object to support RGB values, future support will add second layer as an Alpha channel, in greyscale, due to limitations with Blender. 

The issue arises that multiple layers are being generated on import.

**Comment by HENDRIX-ZT2** [comment]
Is a single layer and can no longer bug out, probably no need for a test. Maybe later?
