### ISSUE TITLE
Export fails : No object selected

### ISSUE THREAD

**Issue by neomonkeus** [niftools/blender_nif_plugin#218]
Traceback (most recent call last):
  File "\io_scene_nif\operators\nif_export_op.py", line 164, in execute
    return nif_export.NifExport(self, context).execute()
  File "\io_scene_nif\nif_export.py", line 200, in execute
    "Please select the object(s) to export,"
io_scene_nif.utility.nif_utils.NifError: Please select the object(s) to export, and run this script again.

location: <unknown location>:-1

**Comment by psi29a** [comment]
Hmm...

**Comment by psi29a** [comment]
I only get this if there is nothing in my scene... how can I duplicate this?

**Comment by nightstrike** [comment]
Don't select any object when you do the export, and you'll get this error.

**Comment by psi29a** [comment]
What would be the preferred message?  Just swallow the exception and send a message back to the user that they have to select an object first?

**Comment by neomonkeus** [comment]
Sorry never really set the expectation on this. Its marks as a usability improvement with the to generate a  userland message. Stacktraces just cause confusion to users. There is a start of implement centralised logging solution would aim to provide this functionality, i.e dept for developers, nice for userland. Best of both world

**Comment by HENDRIX-ZT2** [comment]
Fixed by PR #289.
This issue is now avoided altogether by exporting all of the scene's exportable objects if nothing had been selected. The user is warned (with a user-friendly message) only if nothing could be exported at all.
