### ISSUE TITLE
Variable names refactor in armature_import.py 

### ISSUE THREAD

**Issue by neomonkeus** [niftools/blender_nif_plugin#220]
As part of #219, it was identified that the variable names are not sticking to convention.
The above line would have been easier to see as an unused variable.
There is a mix of object bones and edit bones.

We should use `b_bone_obj` & `b_bone_edit` for variables based on state of bones.

**Comment by HENDRIX-ZT2** [comment]
Fixed by PR #289.
Mirroring the blender type names, I went for `b_edit_bone` (EditBone) and `b_bone` (Bone).
(nb. generic `bone` is still used by some functions operating entirely on NIF data, but all blender bones are now marked for edit / obj mode)

**Comment by neomonkeus** [comment]
We can look at the rest post formatting pass.
