### ISSUE TITLE
Easier way to change scene version

### ISSUE THREAD

**Issue by Dexesttp** [niftools/blender_nif_plugin#227]
# Easier way to change scene version

## Issue description

The scene version currently holds all data used while checking the valilidity of an export action, namely the Version, User Version and User Version 2 (as described in Pull Request #225 ).

However, there is no current way to nicely change the scene version data, as the only way is to edit the Version value in the Blender interface and to replace this value by the wanted version's number.

## Proposed fix

A way to solve this issue would be to add a custom menu to change the Version value, using game names as version descriptor.

This way, the user would be able to select a game name directly instead of inputting a value.

## Additional information

An unneeded step while exporting is the drop down menu used to choose the export version. It should directly be the scene's export version, as it is the only valid one.

Thanks to @Eli2 and @Neomonkeus for their input about this issue.

**Comment by syscrusher1709** [comment]
In attempting to manually edit the data in Blender 2.76b, I find that I can't actually add the property manually at the scene level. Once you set the property name to "niftools", the value shows "API controlled" and cannot be edited. Also, I am unable to delete the property to try again. I can set the value first, with the name defaulted to "prop", and Blender accepts and stores it, but once the name is set to "niftools" the value is discarded.

**Comment by neomonkeus** [comment]
Niftools is a Pointer property to a collection property. The most efficient way to set it at the moment is by switching to the Console Editor view and entering the following. 
'''
bpy.context.scene.niftools.version = 12345
'''
You will probably need to import a mesh to get the  numeric value. There is currently a patch to remove version checking to remove version checking however this issue will be the next priority.
