### ISSUE TITLE
Convert old style string formatting to recommended version

### ISSUE THREAD

**Issue by neomonkeus** [niftools/blender_nif_plugin#228]
The old way of formatting in py2.x used a binary operator, %. By its nature, it can only accept two arguments. 

``` python
print("Output - %i: %i:" % int1, int2)
```

The new way of formatting uses a method. Methods can take any number of arguments.
As such, multiple things to format that need to be passed can be passed as separate arguments. 

``` python
print("Output - {0}, {1}".format(int1, int2)) 
```

The format also allows flexibility in order definition in the case where a function call returns items not in the intended order or even if we want the items to be output at all

``` python
print("Output - {2}, {1}, {0}".format(matrix.decompose()))
```

The old format is still availble by unpacking a tuple into arguments using `*tuple`

``` python
print("First item: {:d}, second item: {:d} and third item: {:d}.".format(*tuple))
```

Good reference - https://mkaz.blog/code/python-string-format-cookbook/

**Comment by yanyu95** [comment]
Hi, I am a newbie. Could I take this one?

**Comment by neomonkeus** [comment]
@yanyu95 Yep, this is one that anyone can take. I have been attempting to clean as I go, but there are probably lots of instances throughout the code that have yet to be done. 
The linked reference is one that I found **recently enough that is really good on this topic. 
See how you get on or if you need any help/direction let me know. 

As a bonus, the link covers some of the more advanced string formatting.

**Comment by HENDRIX-ZT2** [comment]
IMO f-strings win over format(), so I've been sneaking those in whenever I touched a logging message

**Comment by neomonkeus** [comment]
Yeah seen that, makes sense as we move to py 3.7+
