### ISSUE TITLE
Template : PR & Issue

### ISSUE THREAD

**Issue by neomonkeus** [niftools/blender_nif_plugin#231]
Add templates to the repo so that we can have a standardise the way of working.

- [x] Pull Requests
- [x] Issues
- [x] Contributing

https://help.github.com/articles/creating-an-issue-template-for-your-repository/
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

**Comment by neomonkeus** [comment]
Proposal for Pull Requests

@niftools/blender-plugin-reviewer 

# Overview
The following adds a new panel to the UI to allow setting of the Nif Version information.
This information is now optionally set during import & used at export.

# Fixes Known Issues
Fixes xyz

# Documentation
What was documented

# Testing
## Manual
Manual steps

## Automated
Tests written to avoid regression in future

# Additional Information

**Comment by neomonkeus** [comment]
Proposal for Issue Template

@niftools/blender-plugin-reviewer 

# Blender Nif Plugin Version Info

# Overview
The following adds a new panel to the UI to allow setting of the Nif Version information.
This information is now optionally set during import & used at export.

# Steps to reproduce

# Logs

# Blend File 

# Nif File

# Similar Known Issues

# Additional Information

**Comment by GandaG** [comment]
At least for issues, I feel that it's better to provide the issue-er with a description of what to do:

[provide general introduction to the issue logging and why it is relevant to this repository]

## Context

[provide more detailed introduction to the issue itself and why it is relevant]

## Steps to Reproduce

[ordered list the process to finding and recreating the issue]

## Expected result

[describe what you would expect to have resulted from this process]

## Current result

[describe what you you currently experience from this process, and thereby explain the bug]

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## Screenshot

[if relevant, include a screenshot]

## Logs and Files

[provide links to logs file generated during the error as well as the blend and nif files you were using at the time]

## Additional Information

[anything else you feel is relevant]

**Comment by neomonkeus** [comment]
I do like that each section has its own description of content.
If there is no objections, I will use this as the initial draft implementation and open a pull request. Any additions from this discussion issue can added to the implementation.

**Comment by neomonkeus** [comment]
Opened #239 & #240

**Comment by neomonkeus** [comment]
All templates merged
