### ISSUE TITLE
Add Vagrant support.

### ISSUE THREAD

**Issue by GandaG** [niftools/blender_nif_plugin#238]
Vagrant allows for quick and easy environment setup. And it's awesome :p

**Comment by neomonkeus** [comment]
Out if scope : How the environment gets setup is not a concern of this project. The expectation is that it is setup where the documentation suppling a repeatable way to produce that environment but automation of that process or proving alternative ways means more to support.

If you are interested in providing this for the project, it should be written on the @niftools/buildenv project. If you do please supply more detail. Also probably want to know if you have interest in providing an implementation seeing as we already have as buildenv kinda does the same job in a way

**Comment by GandaG** [comment]
Buildenv only supports windows and vagrant would simply replace buildenv. It would make no sense to have a separate repo for 2 files.

**Comment by Dexesttp** [comment]
As said by @neomonkeus , if you want to provide support for Vagrant you're welcome to create it, document it thoroughly then provide it to the repository as a Pull Request. I personally don't see why we would reject such a feature if its usability is explicitly documented and maintainability isn't too tedious to do (as well as documented too).

The point I guess @neomonkeus was trying to make is that this isn't an issue of the Blender plugin. It would only affect contributors to the project and/or people trying to build it from the sources, not the end user. Therefore, an issue about this would be more appropriate in [the niftools/buildenv project](https://github.com/niftools/buildenv).

**Comment by GandaG** [comment]
That is not the point, the vagrant config files are meant to be in the repo they're going to be used in (much like the pydev support files, they're not to be distributed with the plugin but they're still used in development). If you're going to use vagrant the builenv repo is completely unnecessary. This means that I could make the PR againt buildenv, but that repo would have to be become submodule for this one which just seems unnecessarily complex. In case you don't know what vagrant is, [here](https://www.vagrantup.com/docs/why-vagrant/).

The only reason I'm insisting on this is so that people don't start screaming at me when I make the PR :p

**Comment by Dexesttp** [comment]
Ok, and you're right. The PR should be against this repository. However, an *issue* should be against buildenv, as it doesn't affect this repository's goal.

**Comment by GandaG** [comment]
Oh, you were talking about the issue itself! Sorry :p On to buildenv!
