### ISSUE TITLE
Importing files from "Spellbinder The Nexus Conflict" fails

### ISSUE THREAD

**Issue by egore** [niftools/blender_nif_plugin#253]
@niftools/blender-nif-plugin-reviewer 
## Issue Overview

I tried importing some models (e.g. [Robe.NIF.zip](https://github.com/niftools/blender_nif_plugin/files/322520/Robe.NIF.zip)) from the game Spellbinder The Nexus Conflict" (Demo available at https://archive.org/details/SpellbinderTheNexusConflictDemo) using version the NIF blender plugin 2.6.0.

All imports fail with the exception "string to long".
### Blender Nif Plugin Version Info

[Provide version information for the Blender Nif Plugin the issue occurs with, available in Blender in the Add-On section]
### Blender Version Info

[Provide information on which version of Blender the issue is seen]
### Platform information

[Provide a brief overview of what OS your running on]
## Context

[Provide more detailed information to the issue itself and why it is relevant]
## Steps to Reproduce

[Ordered list of the steps required for recreating the issue, including settings]
 #. 
## Expected Result

[Describe what you expected to have resulted from this process]
## Actual Result

[Describe what you currently experience from this process, and thereby explain the bug]
## Possible Fix

[Optional, suggest fixes, improvement or reasons for the bug might have occurred]
## Screenshot

[If relevant, include a screenshot]
## Logs and Files

[Provide logs file generated during the error as well as the blend and nif files are related to the issue]
### Info Bar Output

[Output from the Info View, available at top of Blender viewport, drag to expand]
### Console Output

[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]
### Blend File

[Attach the blend file if issue is reproducible]
### Nif File

[Attach input or output files, samples of what the expected output should be and reproducing the issue]
## Similar Known Issues

[Reference any known issues - https://github.com/niftools/blender_nif_plugin/issues]
## Additional Information

[Anything else you feel is relevant]

**Comment by neomonkeus** [comment]
Hi @egore 

Can you fill out the applicable section of our template.
