### ISSUE TITLE
ValueError: Nif version 30.2.0.3 not supported.

### ISSUE THREAD

**Issue by plumsky** [niftools/blender_nif_plugin#254]
I want ask, when it will be supported?

**Comment by neomonkeus** [comment]
The starting point for versioning support is the nif.xml which describes any given format version
Next is the readers, which in the case of the blender_nif_plugin is pyffi.
Then the plugin can be updated.

However your ticket is more of a forum post as its too broard?
The above looks like something taken from an error log. What is the expected support?

**Comment by L0FKA** [comment]
I know you can look into Noesis (http://www.richwhitehouse.com/index.php?content=inc_projects.php#prjmp91) It's able to handle some parts of the nif v30.1.0.3 (which I was interested in)

But nifskope\nifxml right now doesn't support NiMesh streamed containers so it fail to decode mesh, other things are available tho plus you'd better share your findings here like error log and sample files to play with....
