### ISSUE TITLE
Update minimum supported version information in __init__.py

### ISSUE THREAD

**Issue by beta-tester** [niftools/blender_nif_plugin#258]
@niftools/blender-nif-plugin-reviewer 

## Issue Overview 
wrong version information

### Blender Nif Plugin Version Info
[Provide version information for the Blender Nif Plugin the issue occurs with, available in Blender in the Add-On section] -> Root of this issue really

### Blender Version Info
2, 77, 0

### Platform information
All

## Context
bl_info appears to be wrong, think it should be for blender 2.77

## Steps to Reproduce
 #. Install plugin
 #. View in add-on info section.

## Expected Result
Should display the correct minimum supported Blender versioning following its convention. 
If you want to see the current version of blender, type in bpy.app.version wo the blender python script console.

## Actual Result
If I have installed the minimum supported version, it should correspond to the version displayed by the plugin

## Possible Fix
in the file `/io_scene_nif/__init__.py`
`bl_info = {
...
    "blender": (2, 7, 7),
...
`
should be
`bl_info = {
...
    "blender": (2, 77, 0),
...
`

## Screenshot
N\A

## Logs and Files
N\A

### Info Bar Output
N\A

### Console Output
```
PYTHON INTERACTIVE CONSOLE 3.5.1 (default, Feb 17 2016, 17:09:19) [MSC v.1800 64 bit (AMD64)]

Command History:     Up/Down Arrow
Cursor:              Left/Right Home/End
Remove:              Backspace/Delete
Execute:             Enter
Autocomplete:        Ctrl-Space
Zoom:                Ctrl +/-, Ctrl-Wheel
Builtin Modules:     bpy, bpy.data, bpy.ops, bpy.props, bpy.types, bpy.context, bpy.utils, bgl, blf, mathutils
Convenience Imports: from mathutils import *; from math import *
Convenience Variables: C = bpy.context, D = bpy.data

>>> bpy.app.version
(2, 78, 0)
```
### Blend File
N\A

### Nif File
N\A

## Similar Known Issues
N\A

## Additional Information
Need to decide on minimum supported version.

**Comment by neomonkeus** [comment]
HI @beta-tester, thank you for your reported issue.
In future can you use the template provided for this repo.

**Comment by neomonkeus** [comment]
Updated summary with information provided using template.
Also need to figure out if we need to/can/should support earlier versions, so we can fix the tuple to (2,77,0) but might now be what we really want.

**Comment by neomonkeus** [comment]
@psi29a from an automation perspective, how many (latest - n) versions might be a good number to support, assuming we don't hit backward compatibility issues

**Comment by psi29a** [comment]
Just the supported versions: 
https://docs.python.org/devguide/

Python <= 3.2 are EoL

That means we (for now) need to support Python >= 3.3 and higher.

3.3 is marked for EoL on 2017-09-29 (same as Ubuntu Yakkety).
3.4 is marked for EoL on 2019-03-16.

**Comment by neomonkeus** [comment]
@psi29a  This is in reference to supported Blender versions that we run against

**Comment by psi29a** [comment]
I know, I updated the comment above. :)

**Comment by HENDRIX-ZT2** [comment]
This has been fixed since, can be closed off. @neomonkeus
