### ISSUE TITLE
Shaders : texprop.shader_textures[1] index error

### ISSUE THREAD

**Issue by DokiTeeX** [niftools/blender_nif_plugin#260]
@niftools/blender-nif-plugin-reviewer 

## Issue Overview 
When I try to export an original .nif, it give me this error (screenshot)

### Blender Nif Plugin Version Info
I'm using the 2.6.0 version of NifTools

### Blender Version Info
I'm using the v2.78 of blender

### Platform information
I'm using windows 10 64bit

## Steps to Reproduce
1. Import an ORIGINAL .nif file
2. Export THE SAME ORIGINAL .nif file
3. Get this error

## Expected Result
I would like to get the exported file

## Actual Result
I don't get any exported file

## Possible Fix
I'm searching for theses solutions

## Screenshot
http://imgur.com/a/qt6WU

## Logs and Files
in the screenshot

I would like you to help me get this issue resolved, I'm French and very beginner to these .nif files.

Regards,

**Comment by neomonkeus** [comment]
@DokiTeeX While file were you importing and what game?

**Comment by bqlyhy** [comment]
@neomonkeus I have the  same problem (nif plugin 2.6.0a0.dev4-20-jun-16 / blender 2.78c 64bit / win10 64bit / skyrim / import and export the same nif).
==============log==============
`Read new prefs: C:\Users\cOJzZ\AppData\Roaming\Blender Foundation\Blender\2.78\config\userpref.blend
found bundled python: D:\Program Files\Blender Foundation\Blender\2.78\python
Python Remote Debugging Server not found
pyffi.toaster:INFO:--- fix_scale ---
pyffi.toaster:INFO:  scaling by factor 1.000000
pyffi.toaster:INFO:  ~~~ NiNode [Scene Root] ~~~
pyffi.toaster:INFO:    ~~~ NiStringExtraData [HDT Skinned Mesh Physics Object] ~~~
pyffi.toaster:INFO:    ~~~ NiTriShape [skirt_CH_NPC_Oli.003] ~~~
pyffi.toaster:INFO:      ~~~ NiTriShapeData [] ~~~
pyffi.toaster:INFO:      ~~~ BSDismemberSkinInstance [] ~~~
pyffi.toaster:INFO:        ~~~ NiSkinData [] ~~~
pyffi.toaster:INFO:        ~~~ NiSkinPartition [] ~~~
pyffi.toaster:INFO:      ~~~ BSLightingShaderProperty [] ~~~
pyffi.toaster:INFO:        ~~~ BSShaderTextureSet [] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [NPC] ~~~
pyffi.toaster:INFO:      ~~~ NiNode [NPC Root [Root]] ~~~
pyffi.toaster:INFO:        ~~~ NiNode [NPC COM [COM ]] ~~~
pyffi.toaster:INFO:          ~~~ NiNode [CME Body [Body]] ~~~
pyffi.toaster:INFO:            ~~~ NiNode [CME LBody [LBody]] ~~~
pyffi.toaster:INFO:              ~~~ NiNode [NPC Pelvis [Pelv]] ~~~
pyffi.toaster:INFO:                ~~~ NiNode [CME Pelvis [Pelv]] ~~~
pyffi.toaster:INFO:                  ~~~ NiNode [Butt] ~~~
pyffi.toaster:INFO:                    ~~~ NiNode [CME R PreButtRoot] ~~~
pyffi.toaster:INFO:                      ~~~ NiNode [NPC R PreButt0] ~~~
pyffi.toaster:INFO:                        ~~~ NiNode [CME R PreButt0] ~~~
pyffi.toaster:INFO:                          ~~~ NiNode [NPC R PreButt] ~~~
pyffi.toaster:INFO:                            ~~~ NiNode [CME R PreButt] ~~~
pyffi.toaster:INFO:                              ~~~ NiNode [NPC R ScaleButt] ~~~
pyffi.toaster:INFO:                              ~~~ NiNode [NPC R Butt] ~~~
pyffi.toaster:INFO:                    ~~~ NiNode [CME L PreButtRoot] ~~~
pyffi.toaster:INFO:                      ~~~ NiNode [NPC L PreButt0] ~~~
pyffi.toaster:INFO:                        ~~~ NiNode [CME L PreButt0] ~~~
pyffi.toaster:INFO:                          ~~~ NiNode [NPC L PreButt] ~~~
pyffi.toaster:INFO:                            ~~~ NiNode [CME L PreButt] ~~~
pyffi.toaster:INFO:                              ~~~ NiNode [NPC L ScaleButt] ~~~
pyffi.toaster:INFO:                              ~~~ NiNode [NPC L Butt] ~~~
pyffi.toaster:INFO:                ~~~ NiNode [cOJzZSKFBone1] ~~~
pyffi.toaster:INFO:                  ~~~ NiNode [cOJzZSKFBone2] ~~~
pyffi.toaster:INFO:                    ~~~ NiNode [cOJzZSKFBone3] ~~~
pyffi.toaster:INFO:                      ~~~ NiNode [cOJzZSKFBone4] ~~~
pyffi.toaster:INFO:                        ~~~ NiNode [cOJzZSKFBone5] ~~~
pyffi.toaster:INFO:                          ~~~ NiNode [cOJzZSKFBone6] ~~~
pyffi.toaster:INFO:                            ~~~ NiNode [cOJzZSKFBone7] ~~~
pyffi.toaster:INFO:                              ~~~ NiNode [cOJzZSKFBone8] ~~~
pyffi.toaster:INFO:                                ~~~ NiNode [cOJzZSKFBone9] ~~~
pyffi.toaster:INFO:                ~~~ NiNode [cOJzZSKBBone1] ~~~
pyffi.toaster:INFO:                  ~~~ NiNode [cOJzZSKBBone2] ~~~
pyffi.toaster:INFO:                    ~~~ NiNode [cOJzZSKBBone3] ~~~
pyffi.toaster:INFO:                      ~~~ NiNode [cOJzZSKBBone4] ~~~
pyffi.toaster:INFO:                        ~~~ NiNode [cOJzZSKBBone5] ~~~
pyffi.toaster:INFO:                          ~~~ NiNode [cOJzZSKBBone6] ~~~
pyffi.toaster:INFO:                            ~~~ NiNode [cOJzZSKBBone7] ~~~
pyffi.toaster:INFO:                              ~~~ NiNode [cOJzZSKBBone8] ~~~
pyffi.toaster:INFO:                                ~~~ NiNode [cOJzZSKBBone9] ~~~
pyffi.toaster:INFO:            ~~~ NiNode [CME UBody [UBody]] ~~~
pyffi.toaster:INFO:              ~~~ NiNode [NPC Spine [Spn0]] ~~~
pyffi.toaster:INFO:                ~~~ NiNode [CME Spine [Spn0]] ~~~
pyffi.toaster:INFO:                  ~~~ NiNode [NPC Spine1 [Spn1]] ~~~
pyffi.toaster:INFO:                    ~~~ NiNode [Belly] ~~~
pyffi.toaster:INFO:                      ~~~ NiNode [HDT Belly] ~~~
pyffi.toaster:INFO:                        ~~~ NiNode [NPC Belly] ~~~
pyffi.toaster:INFO:            ~~~ NiNode [LowBodyEviserate] ~~~
pyffi.toaster:INFO:              ~~~ NiNode [NPC RootC [Root]] ~~~
pyffi.toaster:INFO:                ~~~ NiNode [NPC COMC [COM ]] ~~~
pyffi.toaster:INFO:                  ~~~ NiNode [NPC PelvisC [Pelv]] ~~~
pyffi.toaster:INFO:                  ~~~ NiNode [NPC SpineC [Spn0]] ~~~
pyffi.toaster:INFO:                    ~~~ NiNode [NPC Spine1C [Spn1]] ~~~
Traceback (most recent call last):
  File "C:\Users\cOJzZ\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_scene_nif\operators\nif_export_op.py", line 171, in execute
    return nif_export.NifExport(self, context).execute()
  File "C:\Users\cOJzZ\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_scene_nif\nif_export.py", line 236, in execute
    root_block = self.objecthelper.export_node(None, 'none', None, '')
  File "C:\Users\cOJzZ\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_scene_nif\objectsys\object_export.py", line 292, in export_node
    self.nif_export.armaturehelper.export_children(b_obj, node)
  File "C:\Users\cOJzZ\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_scene_nif\armaturesys\armature_export.py", line 226, in export_children
    parent_block, b_obj_child.name)
  File "C:\Users\cOJzZ\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_scene_nif\objectsys\object_export.py", line 212, in export_node
    self.mesh_helper.export_tri_shapes(b_obj, space, parent_block, node_name)
  File "C:\Users\cOJzZ\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_scene_nif\objectsys\object_export.py", line 783, in export_tri_shapes
    b_mat=b_mat, b_obj=b_obj)
  File "C:\Users\cOJzZ\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_scene_nif\texturesys\texture_export.py", line 235, in export_texturing_property
    self.export_nitextureprop_tex_descs(texprop)
  File "C:\Users\cOJzZ\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_scene_nif\texturesys\texture_export.py", line 284, in export_nitextureprop_tex_descs
    shadertexdesc = texprop.shader_textures[1]
  File "C:\Users\cOJzZ\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_scene_nif\modules\pyffi\object_models\xml\array.py", line 67, in __getitem__
    return self._get_item_hook(self, index)
  File "C:\Users\cOJzZ\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_scene_nif\modules\pyffi\object_models\xml\array.py", line 110, in get_item
    return list.__getitem__(self, index)
IndexError: list index out of range

location: <unknown location>:-1

location: <unknown location>:-1`

and the nif file [https://pan.baidu.com/s/1dEFf1VN](url)

**Comment by unixwitch** [comment]
I'm also seeing this with (at least) one of the Skyrim meshes: `meshes\clothes\farmclothes02\f\dress_1.nif`.  To reproduce, just import the mesh and export it again.

It seems to happen with other clothing meshes as well, e.g. `meshes\clothes\blacksmith\m\torso_1.nif`.

Using Blender 2.78c.

**Comment by jonwd7** [comment]
FYI this has cropped up on Discord twice in the past few days.  The issue is very simple:  It's not being exported as Skyrim.  Either you are not selecting Skyrim in the Export settings or you haven't set the User Version and User Version 2 to 12/83.

`export_texturing_property` is only reached if you're attempting to export to Oblivion or earlier.   As for the User Version / User Version 2,  fixing the default in scene_export.py would help with that.

```py
user_version = {
    'OBLIVION' : 11,
    'FALLOUT_3' : 11,
    'SKYRIM' : 12,
    'DIVINITY_2' : 131072
}

user_version_2 = {
    'OBLIVION' : 11,
    'FALLOUT_3' : 34,
    'SKYRIM' : 83,
}
```

**Comment by neomonkeus** [comment]
Added suggested update for Skyrim value part - 
https://github.com/niftools/blender_nif_plugin/pull/280/commits/55b68cc4e242e6c771e8887920be267e28d9fb7b.
Going to port that commit onto develop and update the release.

Fixing underlying issue requires further work.
