### ISSUE TITLE
Export sets bone rotations to 0,0,-90 after multiple imports

### ISSUE THREAD

**Issue by neomonkeus** [niftools/blender_nif_plugin#262]
@niftools/blender-nif-plugin-reviewer 

## Issue Overview 
In certain situations, all bones have a rotation of 0,0,-90 after exporting, regardless of their original value.

### NifTools 2.6.0 Dev 4 (from June 18th 2016),
with added changes from this commit to fix the armature export: https://github.com/niftools/blender_nif_plugin/pull/252/files

### Blender Version Info
Blender 2.78c

### Platform information
[Provide a brief overview of what OS your running on]

## Context
In certain situations, all bones have a rotation of 0,0,-90 after exporting, regardless of their original value. This causes the meshes to appear terribly deformed in-game. 
It seems to only happen if multiple meshes were imported into a file, but behaves strangely.
This makes it impossible add parts of other meshes to the troll AFAIK, since it will ruin your rigging. Which is strange, since I've done this successfully with the Frost Giant mesh before.

## Steps to Reproduce
 
- Importing Troll.nif then immediately exporting is successful.
- Importing Troll.nif then IcicleThinStrip.nif, then exporting only the troll, fails to export bone rotations.
- Importing Troll.nif then IcicleThinStrip.nif, merging them, deleting the icicle trishape, then exporting, is successful.
- Importing Troll.nif then IcicleThinStrip.nif, merging them, deleting the troll, then exporting, fails to export bone rotations.

## Expected Result
Nodes to export with the correct rotation

## Actual Result
Fails to export bone rotation correctly with multiple mesh imports.

## Possible Fix
I now realize that the renaming issue occurs in similar circumstances as this rotation issue -- only when exporting a blend file containing multiple separate meshes that haven't been joined. The fix for this was in the get_bone_name_for_nif function. Running a findstr command, I see that this function is called from 6 places; examining all 6 places, they are all used strictly for indexing purposes (which only need to be internally consistent to work) except for a single call from object_export.py, which saves the value into a variable for export into the Nif. Since the naming error occurs in similar circumstances as rotation error, I believe that the rotation error probably also stems from object_export.py or a function that it uses.

Unfortunately I don't think I will be able to identify the exact issue in the code, since linear algebra isn't my strong point.

## Screenshot
[If relevant, include a screenshot]

## Logs and Files
[Provide logs file generated during the error as well as the blend and nif files are related to the issue]

### Info Bar Output
[Output from the Info View, available at top of Blender viewport, drag to expand]

### Console Output
[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]

### Blend File
[Attach the blend file if issue is reproducible]

### Nif File
Skyrim - Troll.nif, IcicleThinStrip.nif

## Similar Known Issues
[Reference any known issues - https://github.com/niftools/blender_nif_plugin/issues]

## Additional Information
Requires fixing #261 to support vertex groups correctly exporting first

### Workaround
I've figured out an easy way to avoid this problem (and I'm kicking myself for not thinking of it before). If you merge all of the objects into a single mesh with CTRL+J, it will export the bone data correctly. (The NiTriShapes will be grouped under a single NiNode, which causes CTD in-game, but that is easily fixed by parenting the NiTriShapes directly to the root node and deleting the extra NiNode.)

So from this, I am concluding that the issue only occurs when the Object Export protocols need to be used. When it is only an Armature Export there is no issue. This is supported by the fix I found for the other issue (bone naming during export).

**Comment by HENDRIX-ZT2** [comment]
Fixed by PR #289.
