### ISSUE TITLE
ImportError: No module named 'pyffi'

### ISSUE THREAD

**Issue by SigHoovestrong** [niftools/blender_nif_plugin#271]
@niftools/blender-nif-plugin-reviewer 

Hey me again and still running into issues trying install this plugin. Seem now may be file missing and do not know how fix it.

### Blender Version Info
v2.79

## Screenshot
https://i.imgur.com/wgHoiEg.png

**Comment by TagnumElite** [comment]
What file did you use to install the plugin?

**Comment by SigHoovestrong** [comment]
I use the io_scene_nif made it a zip installed it from there. Cause when was trying install it blender_nif_plugin_develop.zip dident want to even show up in blender addons list. 

#Screenshot 
https://i.imgur.com/pI6vnUJ.png

**Comment by TagnumElite** [comment]
Download the file from
https://GitHub.com/niftools/blender_nif_plugin/releases

**Comment by neomonkeus** [comment]
In the previous issue you raised, they linked a video how to install. Also you delete the template contents...

**Comment by SigHoovestrong** [comment]
Aha that seem fix it. Thanks now i can get on with bledering try figure out how to mod. Now as it works i can start having some fun teaching myself model for fo3 and fo4. Other games use nif format.
