### ISSUE TITLE
Unable to import fo4 nif's.

### ISSUE THREAD

**Issue by SigHoovestrong** [niftools/blender_nif_plugin#272]
@niftools/blender-nif-plugin-reviewer 

Having issues when trying import fo4 nif files. fo3 works fine toh. I post screen shot of the error massages i received.

### Blender Version Info
v2.79

## Screenshot
https://i.imgur.com/gNKRfkj.png

**Comment by TagnumElite** [comment]
Fallout 4 and Skyrim SE is currently unsupported.

**Comment by SigHoovestrong** [comment]
Any work being done toward getting fo4 supported?

**Comment by TagnumElite** [comment]
Not until PyFFI has been updated to support FO4 and SSE.

**Comment by SigHoovestrong** [comment]
Right then where do i go check on the progress of PyFFI?

**Comment by jonwd7** [comment]
GitHub is not the place to ask a continuous stream of questions.  We have other more appropriate venues for that.  The first issue you opened (#269) was a question too... one that you had to completely ignore the Issue Template for to submit, which indicates a lot of things, but mostly that you shouldn't be opening tickets on GitHub.

You do not need to create any tickets on PyFFI either.  We already know.  Nobody is working on it, and it's possible that nobody ever will.  FO4 has an official exporter + Elric (an official NIF post-processor) and SSE has the entire existing toolchain for Oldrim + a mostly optional third-party app like Elric, so there's really not much desire to fix things for FO4 and SSE in the first place. 

Given how prolific your posting about this has been, you seem motivated enough to be able to figure out how to use the official FO4 tools.
