### ISSUE TITLE
Error when exporting material with texture without UV

### ISSUE THREAD

**Issue by neomonkeus** [niftools/blender_nif_plugin#276]
@niftools/blender-nif-plugin-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right hand side.
 - [ ] Talk with the developers to ensure its a valid issue

Issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
Exporting the default scene is throwing an exception related to UVs

### Blender Nif Plugin Version Info
[Provide version information for the Blender Nif Plugin the issue occurs with, available in Blender in the Add-On section]

### Blender Version Info
[Provide information on which version of Blender the issue is seen]
blender_nif_plugin-2.6.0a0.dev4

### Platform information
[Provide a brief overview of what OS your running on]

## Context
[Provide more detailed information to the issue itself and why it is relevant]
Attempting to export an object with a material with a texture which does not have UV fails

## Steps to Reproduce
[Ordered list of the steps required for recreating the issue, including settings]

1. Load the default factory settting
2. Load the nif plugin
3. Export the default selected scene

## Expected Result
[Describe what you expected to have resulted from this process]
The cube should export the geom and material data

## Actual Result
[Describe what you currently experience from this process, and thereby explain the bug]
Failing as attempting to process UV data which is not present on the object

## Possible Fix
[Optional, suggest fixes, improvement or reasons for the bug might have occurred]
Looks like there are two issues here 
- Process all the texture slots when they are not used
- Processing the empty UV set

## Screenshot
[If relevant, include a screenshot]

## Logs and Files
[Provide logs file generated during the error as well as the blend and nif files are related to the issue]

### Info Bar Output
```
Executing - Niftools : Blender Nif Plugin v2.6.0 (running on Blender 2.79 (sub 0), PyFFI 2.2.3)
Exporting C:\Users\\Desktop\untitled.nif
Smoothing seams between objects...
Fixed normals on 0 vertices.
Exporting
Exporting NiNode block
Exporting objects
Exporting <bpy_struct, Object("Cube")>
Exporting <bpy_struct, Object("Cube")> as NiTriShape block
Non-UV texture in mesh 'Cube', material 'Material'. Either delete all non-UV textures or create a UV map for every texture associated with selected object and run the script again.
Exporting NiTexturingProperty block
Exporting NiMaterialProperty block
No UV map for texture associated with poly 0 of selected mesh 'Cube'.
Texture is set to use UV but no UV Map is Selected for Mapping > Map
Texture is set to use UV but no UV Map is Selected for Mapping > Map
Texture is set to use UV but no UV Map is Selected for Mapping > Map
Texture is set to use UV but no UV Map is Selected for Mapping > Map
No UV map for texture associated with poly 1 of selected mesh 'Cube'.
Texture is set to use UV but no UV Map is Selected for Mapping > Map
Texture is set to use UV but no UV Map is Selected for Mapping > Map
Texture is set to use UV but no UV Map is Selected for Mapping > Map
Texture is set to use UV but no UV Map is Selected for Mapping > Map
No UV map for texture associated with poly 2 of selected mesh 'Cube'.
Texture is set to use UV but no UV Map is Selected for Mapping > Map
Finished
Traceback (most recent call last):
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\operators\nif_export_op.py", line 171, in execute
    return nif_export.NifExport(self, context).execute()
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\nif_export.py", line 268, in execute
    self.objecthelper.export_node(root_object, 'localspace', root_block, root_object.name)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\objectsys\object_export.py", line 218, in export_node
    self.mesh_helper.export_tri_shapes(b_obj, space, parent_block, node_name)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\objectsys\object_export.py", line 980, in export_tri_shapes
    for uvlayer in range(len(mesh_uvlayers))) \
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\objectsys\object_export.py", line 980, in <genexpr>
    for uvlayer in range(len(mesh_uvlayers))) \
IndexError: list index out of range

location: <unknown location>:-1
```

### Console Output
```found bundled python: C:\Program Files\Blender Foundation\Blender\2.79\python
Python Remote Debugging Server not found
Traceback (most recent call last):
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\operators\nif_export_op.py", line 171, in execute
    return nif_export.NifExport(self, context).execute()
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\nif_export.py", line 268, in execute
    self.objecthelper.export_node(root_object, 'localspace', root_block, root_object.name)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\objectsys\object_export.py", line 218, in export_node
    self.mesh_helper.export_tri_shapes(b_obj, space, parent_block, node_name)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\objectsys\object_export.py", line 980, in export_tri_shapes
    for uvlayer in range(len(mesh_uvlayers))) \
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\objectsys\object_export.py", line 980, in <genexpr>
    for uvlayer in range(len(mesh_uvlayers))) \
IndexError: list index out of range

location: <unknown location>:-1

location: <unknown location>:-1
```

### Blend File
Factory default scene with export

### Nif File
n\a

## Similar Known Issues
#257 Likely failing after introducing these changes

## Additional Information
[Anything else you feel is relevant]

**Comment by HENDRIX-ZT2** [comment]
Can be closed, default cube exports fine regardless of presence or absence of uv data.
