### ISSUE TITLE
Support registering the plugin in Blender 2.8

### ISSUE THREAD

**Issue by neomonkeus** [niftools/blender_nif_plugin#279]
@niftools/blender-nif-plugin-reviewer -

Before creating a new issue, ensure that
 - [x] Read the user documentation.
 - [x] Check that the issue hasn't already been reported.
 - [x] Read through the list of `Helpful resources` links on the right hand side.
 - [x] Talk with the developers to ensure its a valid issue

Issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
This issue is to track changes required to support registration of the Blender Nif Plugin in 2.8
https://wiki.blender.org/wiki/Process/Addons/Guidelines/UpdatingScripts#Class_Property_Registration

## Updating Scripts from 2.7x
This page lists change you may need to make to your scripts so they run in 2.8x.

Please note: The current Python API for Blender 2.8 is under active development and considered unstable (it may change at any time). It is generally recommended add-on authors wait until after the 2.8 Beta is released (planned for late October) to update their code.

## Version Info
Make sure the "blender" key in the bl_info dictionary is set to (2, 80, 0) not (2, 8, 0) or (2, 79, 0)

Example: "blender": (2, 80, 0),
Otherwise, this error is reported:

Exception: Add-on 'ADDON_NAME' has not been upgraded to 2.8, ignoring

## Module Registration
Module registration (bpy.utils.register_module) convenience function has been removed, since keeping track of this information adds unnecessary overhead.

Add-on's should assign their classes to a tuple or list and register/unregister them directly.

eg:
```
classes = (
    FooClass,
    BarClass,
    BazClass,
)

def register():
    from bpy.utils import register_class
    for cls in classes:
        register_class(cls)

def unregister():
    from bpy.utils import unregister_class
    for cls in reversed(classes):
        unregister_class(cls)
```
To avoid having to copy & paste the functions above, you can use bpy.utils.register_classes_factory utility function.
```
classes = (
    FooClass,
    BarClass,
    BazClass,
)
register, unregister = bpy.utils.register_classes_factory(classes)
```
If you have an addon with many classes, the list can be generated using this patch: https://developer.blender.org/P455

## Class Registration
See T52599 for proposal and details.

## Access (bpy.types)
Now only [Header, Menu, Operator, Panel, UIList] are accessed from bpy.types.

Generally scripts access classes they define by importing their own modules, so this should not impact many scripts.

## Naming
In Blender2.7x it was too easy to accidentally register multiple classes with the same name.

To prevent collisions 2.8x enforces naming conventions (already in use across much of Blender's code-base)

This constraint applies to the bl_idname of each class (or the class name which is used if no bl_idname is defined in the class).

These are: UPPER_CASE_{SEPARATOR}_mixed_case, in the case of a menu the regular expression is:

   [A-Z][A-Z0-9_]*_MT_[A-Za-z0-9_]+
Each classes separator is listed below:

Header -> _HT_
Menu -> _MT_
Operator -> _OT_
Panel -> _PT_
UIList -> _UL_
Valid Examples:
```
OBJECT_OT_fancy_tool
SOME_HEADER_HT_my_header
PANEL123_PT_myPanel (lower case is preferred but mixed case is supported).
```
At time of writing names that don't conform to this convention will warn on startup. Eventually we will make this into an error, eg:
```
Warning: 'Oscurart Files Tools' doesn't contain '_PT_' with prefix & suffix
Warning: 'Oscurart Overrides' doesn't contain '_PT_' with prefix & suffix
Warning: 'Oscurart Animation Tools' doesn't contain '_PT_' with prefix & suffix
```
## Class Property Registration
Classes that contain properties from `bpy.props` now use Python annotations,

2.7x:
```
class MyOperator(Operator):
    value = IntProperty()
```

2.8x:
```
class MyOperator(Operator):
    value: IntProperty()
```
Using the 2.7x syntax in 2.8 will result in this error:
```
Warning: class Foo "contains a properties which should be a field!"
```

### Blender Nif Plugin Version Info
[Provide version information for the Blender Nif Plugin the issue occurs with, available in Blender in the Add-On section]

### Blender Version Info
2.8

### Platform information
All

## Context
Blender 2.8 will bring fundamental changes, which are backwards incompatible.
As a knock on effect, the corresponding python api will see changes that we will need to account for

## Additional Information
https://wiki.blender.org/wiki/Process/Addons/Guidelines/UpdatingScripts
https://wiki.blender.org/wiki/Process/Addons/Guidelines/UpdatingScripts#Class_Property_Registration
https://devtalk.blender.org/t/prepping-addons-for-2-8/265/3

**Comment by ParallelMayhem** [comment]
Dang that's pretty cool.
Good luck. I'm looking forward to it.

**Comment by Mowthan** [comment]
> For complete support, indefinitely.
> 
> For incomplete support, I already have a "working" version [here](https://github.com/TagnumElite/blender_nif_plugin/tree/vanilla). ([blender_nif_plugin-3.0.0.zip](https://github.com/niftools/blender_nif_plugin/files/3157346/blender_nif_plugin-3.0.0.zip))
> No collisions, materials import/export, also missing some other things.

I've tried using the files from both of the links provided.
Neither of them give the option to import or export .nif files in blender 2.8

**Comment by mindflvx** [comment]
Same - tried with the #latest build and a one from early May, no go.

**Comment by ParallelMayhem** [comment]
Same, I just tried after I transitioned and it's not working.

**Comment by Ghostwalker71** [comment]
I suggest a slight naming convention change to the plugin Blender2.8_Nif_Plugin-3.0.0 Would allow users to easily see which blender version the file was built against. This would eliminate any confusion as to whether a specific file should work with the version of blender the end users are trying to use.

**Comment by softyoda** [comment]
Is there any version up to date for the 2.80 version of blender ? I've not seen any .nif batch importer and i would like if this addon can convert 200+ nifs.

**Comment by neomonkeus** [comment]
@softyoda We won't support batch conversion.

**Comment by shaidien** [comment]
Support for any version would be great as is NOT ONE WORKS. Great job on nothing guys. Not only have I found it doesn't work this sight is about the hardest to use. My suggestion is move off of github as it sucks and make a working nif plugin and intell you do stop saying it works. It doesn't work.

**Comment by neomonkeus** [comment]
@shaidien Your comments are contributing anything constructive.

**Comment by tokitoki22** [comment]
I think, update for 2.8 with bpy is not so difficult.  but even though after 2.8 released as official, bpy script sitll change . on the other hand, about 2.7 it may not change anymore.  (even though you use 2.7 new beta build)

 I often see same issue, with another importer plug in. the plug in use one package for both version.
with condition to check version.  then user  can report it for 2.7 and 2.8 , the author keep  adapt it at same time.  but 2.8 often change bpy still  (eg recently ,needed to change code for 2.81 about UV things from 2.80) 

So what I hope is,, to keep enhance and remove bug for 2.7 first,, ,, it should be  main subjects.  and hope this plug in will work for SE new meshes too. 

At least about skyrim modding,, I do not find real strong advantage about 2.8. (though I never hope to use 2.4 ,,but 2.7 is still main version for a while,  untill 2.81 will becom stable enough, and it may take at least one year I think so.

**Comment by neomonkeus** [comment]
Converting this to a milestone
