### ISSUE TITLE
Batch Process A Series Of NIFs

### ISSUE THREAD

**Issue by AtomicPerception** [niftools/blender_nif_plugin#281]
I am looking for a way to convert a bunch of NIF files into OBJ or some other format.
I can't figure out how to activate the AddOn from a python script.

Does anyone have an example of how to write a python script to call the NIF loader?

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right hand side.
 - [ ] Talk with the developers to ensure its a valid issue

Issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
[Provide general introduction to the issue and why it is relevant to this repository]

### Blender Nif Plugin Version Info
[Provide version information for the Blender Nif Plugin the issue occurs with, available in Blender in the Add-On section]

### Blender Version Info
[Provide information on which version of Blender the issue is seen]

### Platform information
[Provide a brief overview of what OS your running on]

## Context
[Provide more detailed information to the issue itself and why it is relevant]

## Steps to Reproduce
[Ordered list of the steps required for recreating the issue, including settings]
 #. 

## Expected Result
[Describe what you expected to have resulted from this process]

## Actual Result
[Describe what you currently experience from this process, and thereby explain the bug]

## Possible Fix
[Optional, suggest fixes, improvement or reasons for the bug might have occurred]

## Screenshot
[If relevant, include a screenshot]

## Logs and Files
[Provide logs file generated during the error as well as the blend and nif files are related to the issue]

### Info Bar Output
[Output from the Info View, available at top of Blender viewport, drag to expand]

### Console Output
[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]

### Blend File
[Attach the blend file if issue is reproducible]

### Nif File
[Attach input or output files, samples of what the expected output should be and reproducing the issue]

## Similar Known Issues
[Reference any known issues - https://github.com/niftools/blender_nif_plugin/issues]

## Additional Information
[Anything else you feel is relevant]

**Comment by neomonkeus** [comment]
We don't support batch export of .obj

**Comment by AtomicPerception** [comment]
I can't find any info on how to activate the load from a python script. I can write the batch processor, I am just looking for invocation commands to facilitate some way to activate the AddOn without manually using the menu system.

I have this code so far...
``import bpy
import io_scene_nif
from io_scene_nif.io.nif import NifFile
#filepath = r"S:\nifs\meshes\dungeons\imperial\jail\impjailwall01.nif"
filepath = r"S:\nifs\meshes\dungeons\caves\green\largehall\caveglhall1way01.nif"
#nif_data = NifFile.load_nif(filepath)
#print(dir(nif_data))
cls_NIF = io_scene_nif.nif_import.NifImport
print(dir(cls_NIF))
cls_NIF.execute(bpy.context)

**Comment by neomonkeus** [comment]
See my previous comment about no support being provided.
