### ISSUE TITLE
Not one nif plugin works

### ISSUE THREAD

**Issue by shaidien** [niftools/blender_nif_plugin#294]
@niftools/blender-nif-plugin-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
[Provide a general introduction to the issue and why it is relevant to this repository]

### Blender Nif Plugin Version Info
[Provide version information for the Blender Nif Plugin the issue occurs with, available in Blender in the Add-On section]

### Blender Version Info
[Provide information on which version of Blender the issue is seen]

### Platform information
[Provide a brief overview of what OS your running on]

## Context
[Provide more detailed information to the issue itself and why it is relevant]

## Steps to Reproduce
[Ordered list of the steps required for recreating the issue, including settings]
 #. 

## Expected Result
[Describe what you expected to have resulted from this process]

## Actual Result
[Describe what you currently experience from this process, and thereby explain the bug]

## Possible Fix
[Optional, suggest fixes, improvement or reasons for the bug might have occurred]

## Screenshot
[If relevant, include a screenshot]

## Logs and Files
[Provide logs file generated during the error as well as the blend and nif files are related to the issue]

### Info Bar Output
[Output from the Info View, available at top of Blender viewport, drag to expand]

### Console Output
[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]

### Blend File
[Attach the blend file if the issue is reproducible]

### Nif File
[Attach input or output files, samples of what the expected output should be and reproducing the issue]

## Similar Known Issues
[Reference any known issues - https://github.com/niftools/blender_nif_plugin/issues]

## Additional Information
[Anything else you feel is relevant]

I have tried every version of nif plugin for blender and not one works with blender not even the 2.49 blender as you need to do stuf in nifscope to fool blender to thinking it's a fo nif. So here is ? Is any one who can fix it even still trying or is blender just scrap for skyrim?

**Comment by HENDRIX-ZT2** [comment]
Try this fork: https://github.com/HENDRIX-ZT2/blender_nif_plugin

**Comment by neomonkeus** [comment]
Additionally, @shaidien has been banned.
