### ISSUE TITLE
Receiving the following issue (Multiple)

### ISSUE THREAD

**Issue by woodwards031** [niftools/blender_nif_plugin#300]
![image](https://user-images.githubusercontent.com/55964458/65842480-d5b0b900-e323-11e9-9743-eb0f5355cbb1.png)

**Comment by neomonkeus** [comment]
The mesh has too many vertices as per the last line, with the same being printed in the info window.
The nif format only support 65, 535 per object. 
If you have that many your mesh needs optimisation.
