### ISSUE TITLE
Export crashes if a root node exists, but isn't in selected objects

### ISSUE THREAD

**Issue by HENDRIX-ZT2** [niftools/blender_nif_plugin#309]
@niftools/blender-nif-plugin-reviewer -

# Issue Overview
If you select several objs that are child of some object, but don't select their common root, the root node logic chokes. gotta update the list comprehensions to incorporate selection state

### Blender Nif Plugin Version Info
2.6.0.dev0m4

### Blender Version Info
Blender 2.79

### Platform information
[Provide a brief overview of what OS your running on]

## Context
[Provide more detailed information to the issue itself and why it is relevant]

## Steps to Reproduce
[Ordered list of the steps required for recreating the issue, including settings]
 #. 

## Expected Result
[Describe what you expected to have resulted from this process]

## Actual Result
[Describe what you currently experience from this process, and thereby explain the bug]

## Possible Fix
[Optional, suggest fixes, improvement or reasons for the bug might have occurred]

## Screenshot
[If relevant, include a screenshot]

## Logs and Files
[Provide logs file generated during the error as well as the blend and nif files are related to the issue]

### Info Bar Output
[Output from the Info View, available at top of Blender viewport, drag to expand]

### Console Output
[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]

### Blend File
[Attach the blend file if the issue is reproducible]

### Nif File
[Attach input or output files, samples of what the expected output should be and reproducing the issue]

## Similar Known Issues
[Reference any known issues - https://github.com/niftools/blender_nif_plugin/issues]

## Additional Information
[Anything else you feel is relevant]

**Comment by neomonkeus** [comment]
Would like to have a dedicated object that is the scene root.

**Comment by HENDRIX-ZT2** [comment]
Currently if there is no proper root object, an auto root is generated on the nif end. That works fine, if all or no objects or only objects without parents (pseudo-roots) are selected.

This is not a bug with the roots logic per se but more an interference with the export only selected objects feature.
If we generated a blender root object in this situation it would mess up the parenting and possibly break things such as armature skinning.

**I would propose to get rid of export only selected. It is too easy to change the selection state unwittingly. If we want to limit exported objects, we coud use b_obj.hide bool or check if the b_obj occurs in any visible layer / collection.**

**Comment by HENDRIX-ZT2** [comment]
I should clarify, we create a root object on import. The virtual root object is only created on the nif end if the user messes up the blender scene so it has more than one root object.
