### ISSUE TITLE
can't import / export nifs 

### ISSUE THREAD

**Issue by Jaume96** [niftools/blender_nif_plugin#320]
@niftools/blender-nif-plugin-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
[Provide a general introduction to the issue and why it is relevant to this repository]
When importing a mesh (Vanilla DaedricBowSkinned.nif) it apears black and when I try to edit it blender crashes to desktop. Further more, opening a older file with skyrim ready bow and try to export it, the pluggin fails and send the next warning: AtributeError: 'Texture' has no atribute 'export_bs_shader_property'

If I delete the material, The export works, but it results in a Nitrisjape without UVs

### Blender Nif Plugin Version Info
[Provide version information for the Blender Nif Plugin the issue occurs with, available in Blender in the Add-On section]
blender_nif_plugin-2.6.0a0.dev4.20200111

### Blender Version Info
[Provide information on which version of Blender the issue is seen]
version of Blender 2.79b

### Platform information
[Provide a brief overview of what OS your running on]

Windows 10 x64
## Context
[Provide more detailed information to the issue itself and why it is relevant]

## Steps to Reproduce
[Ordered list of the steps required for recreating the issue, including settings]

Open blender, activate the pluggin, try to import daedric bow
 #. 

## Expected Result
[Describe what you expected to have resulted from this process]
1. Import and edit daedric bow meshes
2. Export an actual rigged and skinned custom bow

## Actual Result
[Describe what you currently experience from this process, and thereby explain the bug]
1. Import the mesh totaly black and crahs when go to edit mode
2.Dont export anything at all or export a mesh without UVs

## Possible Fix
[Optional, suggest fixes, improvement or reasons for the bug might have occurred]

## Screenshot
[If relevant, include a screenshot]

![image](https://user-images.githubusercontent.com/60271663/73096555-5bfd9600-3ee5-11ea-9867-6b09f9273baa.png)

## Logs and Files
[Provide logs file generated during the error as well as the blend and nif files are related to the issue]

### Info Bar Output
[Output from the Info View, available at top of Blender viewport, drag to expand]

### Console Output
[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]

### Blend File
[Attach the blend file if the issue is reproducible]

### Nif File
[Attach input or output files, samples of what the expected output should be and reproducing the issue]

## Similar Known Issues
[Reference any known issues - https://github.com/niftools/blender_nif_plugin/issues]

## Additional Information
[Anything else you feel is relevant]

**Comment by neomonkeus** [comment]
This looks to be a Skyrim nif. The version of the plugin has removed support for it as the material system is being rewritten. I thought that it was mentioned in the release notes, I will update it to reflect the fact that Skyrim materials are unsupported until the material updates are made.
