### ISSUE TITLE
Fallout 3/new vegas materials import

### ISSUE THREAD

**Issue by gambikules** [niftools/blender_nif_plugin#321]
@niftools/blender-nif-plugin-reviewer -

# Issue Overview
No material loaded from fallout nifs

### Blender Nif Plugin Version Info
2.60

### Blender Version Info
[Provide information on which version of Blender the issue is seen]
2.79
### Platform information
[Provide a brief overview of what OS your running on]
Windows 10 
## Context
In old nif version for 2.49 all loaded models have materials with textures.
(i have extract all nifs and dds)

## Steps to Reproduce
Just import static or skinned nif
 #. 

## Expected Result
Like in version 2.5< for Blender 2.49 loaded materials with textures

## Actual Result
White materials named "noname.001"  ...

## Logs and Files
No errors

### Info Bar Output
Nothing

### Console Output
https://drive.google.com/open?id=1mZHtP2n6wG2-qjxyi2fqTxj2OmwFMgxa

### Nif File
Need extract nif with dds, without not work its normal, but when extracted in latest Nif plugin versions work

## Additional Information
Versions Blender 2.69 and nif plugin for 2.49 no problems detected

**Comment by neomonkeus** [comment]
Can you provide the actual version of the nif plugin. If you are using the pre-release version, materials are currently being rewritten as per the description - https://github.com/niftools/blender_nif_plugin/releases

**Comment by gambikules** [comment]
Blender Nif Plugin 2.6.0.dev4 - Dev Branch - 2019-11-24

**Comment by neomonkeus** [comment]
Yep, both versions contains partial support for the new material system, which has reconnected support for Ni*Property nodes, ie NiMaterialPropertwhich and Fallout/Skyrim is a WIP. 
#319 has more of the nodes covered, mainly the newer BSShaderProperty nodes, so watch this space.
