### ISSUE TITLE
Help installing on Blender 2.79

### ISSUE THREAD

**Issue by doktorsavage** [niftools/blender_nif_plugin#323]
Did a fresh install of Blender 2.79, then installed the plugin version "2.6.0.dev4".

Getting errors on trying to import a nif file from Fallout 4, tried other nif files from fallout 4 with no avail.
![image](https://user-images.githubusercontent.com/62444731/77198724-c590bf80-6aa4-11ea-9ee1-eb7c6f6f54e3.png)

Am I missing something in regards to installing this plugin?

**Comment by neomonkeus** [comment]
F04 is not supported.
