### ISSUE TITLE
ValueError: deepcopy: classes BSFadeNode and NiTriShape unrelated

### ISSUE THREAD

**Issue by EnemyAI** [niftools/blender_nif_plugin#328]
@niftools/blender-nif-plugin-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview

Everytime I try to export a model with BSFadeNode, this error appears: 

ValueError: deepcopy: classes BSFadeNode and NiTriShape unrelated

The export was working properly on previous versions of the plugin, also the shader settings were moved from the objects tab to the material tab.

### Blender Nif Plugin Version Info

blender_nif_plugin-2.6.0a0.dev4-2018-07-30

### Blender Version Info

Blender 2.79

### Platform information

Windows 7 x64 bits

## Context

Export/Import NOT working.
Exporting as just NiNode seems to be working, but that still causes lots of issues on Nifskope.
Exporting a single object with multiple materiais (more than one NiTriShapeData) is NOT working.

## Steps to Reproduce

Scene tab - Nif Version: 0
                 - User Version: 12
                 - User Version2: 83

Object tab - Nif Root Node: BSFadeNode
                  - BSX Flags: 130
                  - Consistency Flag: CT_STATIC
                  - Object Flag: 14

Textures as UV Map
Shader: BSLightning Shader Property

 #. 

## Expected Result

Exporting files as .NIF with BSFadeNode working properly.

## Actual Result

ERROR:
Everytime I try to export a model with BSFadeNode, this error appears: 

## Possible Fix
[Optional, suggest fixes, improvement or reasons for the bug might have occurred]

## Screenshot

![image](https://user-images.githubusercontent.com/63529031/79075176-85011c00-7cc7-11ea-9d88-71189a7a53c5.png)

## Logs and Files
[Provide logs file generated during the error as well as the blend and nif files are related to the issue]

### Info Bar Output
[Output from the Info View, available at top of Blender viewport, drag to expand]

### Console Output
[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]

### Blend File
[Attach the blend file if the issue is reproducible]

### Nif File
[Attach input or output files, samples of what the expected output should be and reproducing the issue]
[Isolated.blend.zip](https://github.com/niftools/blender_nif_plugin/files/4517889/Isolated.blend.zip)

## Similar Known Issues
[Reference any known issues - https://github.com/niftools/blender_nif_plugin/issues]

## Additional Information
[Anything else you feel is relevant]

**Comment by neomonkeus** [comment]
@EnemyAI I have readded the template. Please fill it out correctly as it will help with reproducing and fixing the issue. Thanks.

**Comment by neomonkeus** [comment]
Can you try with the latest version of the plugin, you are using one from 2 years ago - 2018-07-30

**Comment by Candoran2** [comment]
I (and other people on the Arcane University) have this problem as well, with the *newer* version of the plugin. The older version (i.e. from 2018-07-30) worked/works just fine.

**Comment by neomonkeus** [comment]
@Candoran2 Can you help to reproduce/provide the files that are missing from the issue template.

**Comment by Candoran2** [comment]
Yes, sure. Sorry it took so long, I was trying to recreate the issue with a regular barrel. Here is the blend file for which the nif export does not work with the newer plugin version:
https://cdn.discordapp.com/attachments/702566403605266435/702567007052103710/Isolated.blend
If you like, I can also provide the correcly exported nif file from the old plugin version, or the NiNode exported version for the old/new plugin.
Interestingly, it doesn't seem to happen with every file. Whilst trying to recreate the issue with the regular barrel, it didn't throw that error.

**Comment by neomonkeus** [comment]
I suspect it has to do with muli-node support. I have attached the blend file.
There is currently some rework ongoing with how we import nodes and the grouping system, so this issue might just disappear as part of that.

**Comment by Candoran2** [comment]
This is the original nif file, which was modified in Blender (mostly removed the other NiTriShapes):
https://cdn.discordapp.com/attachments/702566403605266435/706140923452588052/ruins_largedoor01Opened.nif
