### ISSUE TITLE
Export Zoo Tycoon 2 Error

### ISSUE THREAD

**Issue by horse14t** [niftools/blender_nif_plugin#330]
@niftools/blender-nif-plugin-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [x] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
Cant export edited gift nif from Zoo Tycoon 2

### Blender Nif Plugin Version Info
Blender Nif Plugin 2.6.0.dev4 - Dev Branch - 2020-03-22

### Blender Version Info
Blender 2.79

### Platform information
Windows 10

## Context
Imported nif won't export if edited in any way.

## Steps to Reproduce
1. Import a gift nif from Zoo Tycoon 2
2. Edit it in any way, example deleting a part of the mesh and than closing the gap
3. Export

## Expected Result
An exported nif file

## Actual Result
Error and no exported nif file.

## Possible Fix
[Optional, suggest fixes, improvement or reasons for the bug might have occurred]

## Screenshot
![image](https://user-images.githubusercontent.com/43920874/79149448-09ad7200-7d7c-11ea-9ca8-3fc9ab02088c.png)

## Logs and Files
[Provide logs file generated during the error as well as the blend and nif files are related to the issue]
Can't find it :/

### Info Bar Output
[Output from the Info View, available at top of Blender viewport, drag to expand]
This?
![Capture 3](https://user-images.githubusercontent.com/43920874/79152457-1aacb200-7d81-11ea-886d-b2f005d8b934.PNG)

### Console Output
[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]
![Capture 4](https://user-images.githubusercontent.com/43920874/79152589-547db880-7d81-11ea-88f1-766f7f3d91ab.PNG)

### Blend File
[Attach the blend file if the issue is reproducible]
[Gift_Nif.blend](https://www.dropbox.com/s/967ldu3m54unxvv/Gift_Nif.blend?dl=0)

### Nif File
[Attach input or output files, samples of what the expected output should be and reproducing the issue]
[Gift Nif.zip](https://www.dropbox.com/s/mxai4pqoe13phoc/Gift%20Nif.zip?dl=0)

## Similar Known Issues
[Reference any known issues - https://github.com/niftools/blender_nif_plugin/issues]

## Additional Information
[Anything else you feel is relevant]

-----

Hello,

So I'm working with an object nif that looks like this in Nifskope:
![image](https://user-images.githubusercontent.com/43920874/79083501-83455180-7ce3-11ea-9b89-4d6cee635f96.png)
and I can't even do a single thing meshing it without getting this error when exporting:
![Error](https://user-images.githubusercontent.com/43920874/79083523-a53ed400-7ce3-11ea-995b-8a5ec409177e.png)
(Pops up after even just clicking X-Mirror!)
Can someone help me please?
I'm using Blender 2.79 and the latest version of the plugin.

I also get this when exporting after doing nothing (Just Importing and then Exporting it)
However the nif does actually export:
![image](https://user-images.githubusercontent.com/43920874/79083743-ef748500-7ce4-11ea-88a7-2f8d813d0020.png)

**Comment by neomonkeus** [comment]
@horse14t I have re-added the template. 
Please fill out the template as it enables us to help you.

**Comment by horse14t** [comment]
> 
> 
> @horse14t I have re-added the template.
> Please fill out the template as it enables us to help you.

Oh sorry!
I filled it out the best I could. Couldn't find where the log files are kept though :/

**Comment by HENDRIX-ZT2** [comment]
Probably related / same issue: https://github.com/niftools/blender_nif_plugin/issues/309

**Comment by neomonkeus** [comment]
Thanks @horse14t for filling out the details. "Logs" is just the section header, you provided exactly what we are looking for with the output from the report ui and the console window.

**Comment by horse14t** [comment]
> 
> 
> Thanks @horse14t for filling out the details. "Logs" is just the section header, you provided exactly what we are looking for with the output from the report ui and the console window.

Oh okay! I tried to look it up but got mixed messages. 
Hope it can be patched out! The nifscripts for Blender 2.49b also don't work for gifts which sucks :(
The Bfb plugin works at least but I do like to have the option to work with both :)
