### ISSUE TITLE
Cannot Export Skyrim Skeleton

### ISSUE THREAD

**Issue by Rarity1** [niftools/blender_nif_plugin#331]
@niftools/blender-nif-plugin-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
The program throws an error every time I try to export any functional skyrim skeleton. 
I dont actually know if you guys consider skeletons nifs but I do so I thought thats a pretty important reason to report it.

### Blender Nif Plugin Version Info
Blender Nif Plugin 2.6.0.dev4 - Dev Branch - 2020-03-22

### Blender Version Info
Blender 2.79b x86

### Platform information
Windows 10

## Context
It seems to be a pretty simple issue. It just doesnt like exporting skeletons. 

## Steps to Reproduce
 1. Open up a skeleton blend file or nif file in blender.
 2. Export that skeleton file as nif without changing anything.

## Expected Result
I expect it to at least output a nif even if it has things missing.

## Actual Result
Upon trying to export a file that is a functional skyrim skeleton it throws "AttributeError: 'Collision' object has no attribute 'export_bounding_box'
I dont really understand what the bug is. I am new to this whole modeling software and exporting. 

## Possible Fix
No idea. I think the plugin just doesnt have the code for exporting skeleton specific objects. 

### Info Bar Output
![Screenshot (12)](https://user-images.githubusercontent.com/7364947/79248601-05e82100-7e4a-11ea-8680-b6c5107a31a3.png)

### Console Output
![Screenshot (12)](https://user-images.githubusercontent.com/7364947/79248573-ff59a980-7e49-11ea-8023-5d1f8a808b99.png)

### Nif File
[Skyrim skeleton files.zip](https://github.com/niftools/blender_nif_plugin/files/4476433/Skyrim.skeleton.files.zip)

## Similar Known Issues
I wouldnt know whats similar. I just know I couldnt find my specific error. 

## Additional Information
I really dont know if you guys are even trying to support skeletons. I just know they count as nif files.

**Comment by neomonkeus** [comment]
Thanks for the great report, much appreciated.
Export should work for skeleton, but the information you provided will make it easy to track down.

**Comment by neomonkeus** [comment]
I had a look at this issue today.
The error message doesn't correspond with the lines of code that I have here.
I think you might have an older version of the plugin installed, or Blender didn't override the files correctly when it installed. Can you reinstall and see if the issue persists?

**Comment by Rarity1** [comment]
Yeah I can try that. Do I need to run blender in administrator mode when installing addons?

**Comment by neomonkeus** [comment]
The Skyrim texture update hasn't been as widely tested so not surprised to have issues.
Interestingly it seems to be trying to export out a NiTextureingProperty, so that narrows it down. Thanks for the output above.

**Comment by Rarity1** [comment]
Apparently Ive been exporting with the wrong settings so sorry If I caused any confusion.

Ive tried the new version you released and it has a different problem. It wont let you export a skeleton because the import generates capsules for collision but the export doesnt seem to know what to do with them.
![Screenshot (16)](https://user-images.githubusercontent.com/7364947/80058696-f75bd280-84f7-11ea-8a6c-a1c25fea5913.png)

Nifs that have no collision capsules dont have any problems exporting and are 100% perfect.

**Comment by neomonkeus** [comment]
I have seen the above issue before
