### ISSUE TITLE
Error importing BSEffectShader without Controller.

### ISSUE THREAD

**Issue by Candoran2** [niftools/blender_nif_plugin#339]
@niftools/blender-nif-plugin-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
When I use the import > nif function on a normal weapon mesh, such as that of the iron dagger (converted to LE with Nif Optimizer, as I do not have LE), it throws the error `'NoneType' object has no attribute flags.`. This stops the import. It also occurs when every branch in the scene has been removed except the one containing the BSEffectShader.

### Blender Nif Plugin Version Info
The Nif Plugin version was version 2.6.0 from 2020-04-21.

### Blender Version Info
The issue is seen in Blender 2.79.

### Platform information
I am running on 64-bit Windows 10.

## Context
This is relevant when you want to modify vanilla weapons, or when creating new weapons. When creating a new weapon, a person might want to import a vanilla file to get the handle position and scale right, which is made difficult (though not impossible, removing the BSEffectShader fixes it).

## Steps to Reproduce
 #. Import irondagger.nif via File > Import > NetImmerse/Gamebryo (.nif). 
 #. This results in the error.

## Expected Result
I expected the file to correctly import, with all the blood meshes.

## Actual Result
Instead, it halts at the import of the DaggerBloodFX, not importing the NiTriShapes actually used for the weapon model or the scabbard model.

## Possible Fix
I have fixed this issue myself by adding the condition `if (bs_effect_shader_property.controller):` before the offending line ( `b_mat.niftools_alpha.textureflag = bs_effect_shader_property.controller.flags`). This has allowed complete import of the nif file. The only remaining BSEffectShader issue that, upon re-export, the soft falloff depth of the BSEffectShaderProperty defaults to 0, and the greyscale texture is set to be the same as the source texture, even when the greyscale texture was not set before (as is the case in weapons).

## Screenshot
Partially imported iron dagger: 
![image](https://user-images.githubusercontent.com/45334438/80917112-33dfc780-8d5d-11ea-9295-8eed1fab1d62.png)

## Logs and Files
[Provide logs file generated during the error as well as the blend and nif files are related to the issue]

### Info Bar Output
[Output from the Info View, available at top of Blender viewport, drag to expand]

### Console Output
```
File "C:\Users\Candoran2\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\modules\nif_import\property\shader\bsshaderproperty.py", line 179, in import_bs_effect_shader_property
    b_mat.niftools_alpha.textureflag = bs_effect_shader_property.controller.flags
AttributeError: 'NoneType' object has no attribute 'flags'
```
### Blend File
File after failed import:
https://cdn.discordapp.com/attachments/702566403605266435/706515231979077652/FXError.blend

### Nif File
Iron dagger nif file:
https://cdn.discordapp.com/attachments/702566403605266435/706515307014914138/irondagger.nif

## Similar Known Issues
[Reference any known issues - https://github.com/niftools/blender_nif_plugin/issues]

## Additional Information
[Anything else you feel is relevant]

**Comment by neomonkeus** [comment]
Not a clean merge to 2.8
