### ISSUE TITLE
Messed up skeleton weights & some vertices not loaded

### ISSUE THREAD

**Issue by aymen157** [niftools/blender_nif_plugin#357]
@niftools/blender-nif-plugin-reviewer -

Before creating a new issue, ensure that
 - [x] Read the user documentation.
 - [x] Check that the issue hasn't already been reported.
 - [x] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
as title states, importing nifs doesn't get the weights of bones valid (or possibly there's an offset between model & bones caused by a bug?) also many objects in the nif are not loaded

## Version Information
Blender Nif Plugin 2.6.0.dev4 
### Blender Nif Plugin Version Info
[Provide version information for the Blender Nif Plugin the issue occurs with, available in Blender in the Add-On section]

### Blender Version Info
Blender 2.80

### Platform information
Windows

## Context
[Provide more detailed information to the issue itself and why it is relevant]

## Steps to Reproduce
[Ordered list of the steps required for recreating the issue, including settings]
 #. 

## Expected Result
[Describe what you expected to have resulted from this process]

## Actual Result
[Describe what you currently experience from this process, and thereby explain the bug]

## Possible Fix
[Optional, suggest fixes, improvement or reasons for the bug might have occurred]

## Screenshot
https://imgur.com/a/yH3nJUP

## Logs and Files
[Provide logs file generated during the error as well as the blend and nif files are related to the issue]

### Info Bar Output
[Output from the Info View, available at top of Blender viewport, drag to expand]

### Console Output
[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]

### Blend File
[Attach the blend file if the issue is reproducible]

### Nif File
https://srv-file5.gofile.io/download/g8ox7H/GXA00.nif

## Similar Known Issues
[Reference any known issues - https://github.com/niftools/blender_nif_plugin/issues]

## Additional Information
[Anything else you feel is relevant]

**Comment by neomonkeus** [comment]
Can you upload the file as a zip.

**Comment by aymen157** [comment]
There you go : https://gofile.io/d/lVo8ZI
Also by the way there are Nodes that have wrong names or are unnamed and some parts of the model have weird UV

**Comment by HENDRIX-ZT2** [comment]
Also upload the KF in question please.

**Comment by aymen157** [comment]
here's the kf file
[b_attack.zip](https://github.com/niftools/blender_nif_plugin/files/4687824/b_attack.zip)

**Comment by HENDRIX-ZT2** [comment]
Thanks, but in fact all animations import correctly as blender actions:
![grafik](https://user-images.githubusercontent.com/28632661/83002690-a3b83980-a00d-11ea-9528-bca4c1793314.png)

**Comment by aymen157** [comment]
That's strange for some reasons, they don't get exported

**Comment by HENDRIX-ZT2** [comment]
Anim export technically works fine too, if it doesn't work for the specific game you want to export to, please raise a separate issue.
