### ISSUE TITLE
Need a "disable scaling" checkbox with kf import

### ISSUE THREAD

**Issue by Heaverno** [niftools/blender_nif_plugin#372]
using newest develop version. anims are from skyrim LE community.
some kf animations turns out to have random scale problems, they have different behavior like shaking, suddenly scales to large size, even scales between 2 negative scales.
i checked NLA editor and found out that there are scale keys and i can delete them to deal with the problem.
but skeletal anims most time does not scale, right? 
please add a disable scaling checkbox to kf import.

**Comment by Heaverno** [comment]
Plus unusually finger displacement, almost occurs in every anims.
A proper character anim should not have location key too.

**Comment by HENDRIX-ZT2** [comment]
Please upload sample nif and kf files so we can replicate the issue.

**Comment by Heaverno** [comment]
[xd.zip](https://github.com/niftools/blender_nif_plugin/files/4935249/xd.zip)
including: newest XPMSE skeleton for skyrim LE .nif
                several .kf anims that have scale and location keys consisted after been imported.
I do think a brutal method would be fair enough.

**Comment by HENDRIX-ZT2** [comment]
The keys are there in nifskope so I don't think they should just be discarded. Does not look like a bug.

**Comment by Heaverno** [comment]
oh, now I see. The problem goes down when I convert hkx to kf. Thx alot anyway.
