### ISSUE TITLE
Sub Issue : #84 : Create a Capsule Primitive for use with Collisions

### ISSUE THREAD

**Issue by neomonkeus** [niftools/blender_nif_plugin#63]
Currently a cylinder is the closest representation to the meta-capsule shape that is used create a bhkCapsuleShape. Adding our own custom primitive will allow us to both visually represent the shape  due to lack of viewport visualisation internally with Blender and gives us control to ensure the shape is easier to read data from.

Note: Investigate current Bullet integration roadmap and see its affect on collision system in terms of collision bounds in general.

Ref: #84

**Comment by HENDRIX-ZT2** [comment]
Fixed by PR #289. Blender now has capsule draw type so we can retain the box primitives.
bhkCapsuleShapes import, visualize and export fine (eg. Skyrim dog `skeleton.nif`).
