### ISSUE TITLE
browse button for adding keyframe or face gen files cannot be used

### ISSUE THREAD

**Issue by Ghostwalker71** [niftools/blender_nif_plugin#93]
Blender doesn't support opening separate file browser instances. once the import function begins the box to add the keyframe or the facegen file can not be utilized unless the file path is manually input.

One option is to set the nif file in the same manner as the kf and egm files in a selection box then have a final execution button to begin the actual importing.

**Comment by HENDRIX-ZT2** [comment]
Kf issue fixed by PR #289 by using a separate import operator. Egm issue still pending.

**Comment by HENDRIX-ZT2** [comment]
EGM cannot be easily externalized as it relies on the vertex map built during nif import. I __think__ blender 2.8 lets you open multiple file browsers at once.

**Comment by HENDRIX-ZT2** [comment]
Since we no longer use the vertex map, EGM can now be moved out into its own operator.
